In [10]:
pip install wget


  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9657 sha256=5b7cbd69431115ac208e71884929b12c9d559ca3cb732dd85ed1da5735068ac2
  Stored in directory: c:\users\acer\appdata\local\pip\cache\wheels\04\5f\3e\46cc37c5d698415694d83f607f833f83f0149e49b3af9d0f38
Successfully built wget


In [12]:
import numpy as np
import pandas as pd
import wget

Question 1

What's the version of NumPy that you installed?

You can get the version information using the __version__ field:

In [4]:
np.__version__

'1.21.5'

Question 2

Getting the data

In [13]:
url = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
wget.download(url)

100% [..........................................................................] 1475504 / 1475504

'data.csv'

In [14]:
data = pd.read_csv('data.csv')
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

How many records are in the dataset?

In [15]:
data.shape

(11914, 16)

Question 3

Who are the most popular car manufacturers (top-3) according to the dataset?

In [16]:
data.sort_values('Popularity').head()

Make Model  Year             Engine Fuel Type  Engine HP  \
2116   Spyker    C8  2009  premium unleaded (required)      400.0   
2117   Spyker    C8  2009  premium unleaded (required)      400.0   
2118   Spyker    C8  2009  premium unleaded (required)      400.0   
5202  Genesis   G80  2017             regular unleaded      311.0   
5204  Genesis   G80  2017             regular unleaded      311.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
2116               8.0            MANUAL  rear wheel drive              2.0   
2117               8.0            MANUAL  rear wheel drive              2.0   
2118               8.0            MANUAL  rear wheel drive              2.0   
5202               6.0         AUTOMATIC  rear wheel drive              4.0   
5204               6.0         AUTOMATIC   all wheel drive              4.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
2116  Exotic,High-Performance      Compact         Coupe           18   
2117  Exotic,High-Performance      Compact   Convertible           18   
2118  Exotic,High-Performance      Compact         Coupe           18   
5202       Luxury,Performance        Large         Sedan           28   
5204       Luxury,Performance        Large         Sedan           25   

      city mpg  Popularity    MSRP  
2116        13           2  209990  
2117        13           2  219990  
2118        13           2  209990  
5202        18          21   41400  
5204        16          21   43900

Chevrolet, Ford, Toyota

Question 4

What's the number of unique Audi car models in the dataset?

In [17]:
data[data.Make == 'Audi'].Model.nunique()

34

Question 5

How many columns in the dataset have missing values?

In [18]:
data.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

5 Columns

 Question 6 

1. Find the median value of "Engine Cylinders" column in the dataset.
2. Next, calculate the most frequent value of the same "Engine Cylinders".
3. Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
4.  Now, calculate the median value of "Engine Cylinders" once again.

In [19]:
data['Engine Cylinders'].median()

6.0

In [20]:
data['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [21]:
data['Engine Cylinders'] = data['Engine Cylinders'].fillna(4)

In [22]:
data['Engine Cylinders'].median()

6.0

No, Median has not changed

Question 7

1. Select all the "Lotus" cars from the dataset.
2. Select only columns "Engine HP", "Engine Cylinders".
3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the value of the first element of w?

In [24]:
data[data.Make == 'Lotus'].head()

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   
3915  Lotus  Elise  2010  premium unleaded (required)      189.0   
3916  Lotus  Elise  2010  premium unleaded (required)      218.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   
3915  Exotic,High-Performance      Compact   Convertible           27   
3916  Exotic,High-Performance      Compact   Convertible           26   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250  
3915        21         613  47250  
3916        20         613  54990

In [25]:
data[data.Make == 'Lotus'][[ "Engine HP", "Engine Cylinders"]].head()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0

In [26]:
data[data.Make == 'Lotus'][[ "Engine HP", "Engine Cylinders"]].drop_duplicates()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [27]:
X = data[data.Make == 'Lotus'][[ "Engine HP", "Engine Cylinders"]].drop_duplicates().values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [28]:
XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [29]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [30]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [31]:
w = inv_XTX.dot(X.T).dot(y)
w

array([  4.59494481, -63.56432501])

the first element of w is 4.5949